### ISSUE TITLE
Prevent snapping between conflicting commands

### ISSUE THREAD

**Issue by jdloft** [leomwu/agario-bot#30]
Many commands can conflict if different sized players get near, etc. but this creates a snapping moving effect that doesn't look natural and can often just waste time. Perhaps the bot should prioritize a command and have a cool down before any other command takes over.

**Comment by LeoWuVinci** [comment]
There's very little inertia in the game engine so I decided to not try to focus too much on finding ways to make it more optimal.  More importantly it has a foundation so that anyone can fork the code and contribute in that manner.  Think of what I've done as "example code".  That said, cool down IS  implemented for every consideration.
